services:
    esportpredictionbot:
        build:
            context: .
            dockerfile: Dockerfile
        command: ['node', 'dist/bot.js']
        restart: always
        environment:
            - CLIENT_ID=${CLIENT_ID}
            - GUILD_ID=${GUILD_ID}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
