services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./data:/data

volumes:
    data:
